server: "hub-cloud.browserstack.com"
user: "tiagooliveirasil1"
key: "8Dsm4MknzeEDhxxreh3D"

common_caps:
  "build": "capybara-browserstack"
  "browserstack.debug": true

browser_caps:
  -
    "browser": "chrome"
  -
    "browser": "firefox"
  -
    "browser": "internet explorer"
  -
    "browser": "safari"
